boardLists = [
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r# #r",
    " # #r# #",
    "# #w# # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r# #r",
    " # #r# #",
    "# #w# # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r# ",
    "r#r#r#r#",
    "#r#r# #r",
    " # #r# #",
    "# #w# # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r# ",
    "r#r#r#r#",
    "# #r# #r",
    " #r#r# #",
    "# #w# # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r# #r# ",
    "r#r#r#r#",
    "# #r# #r",
    " #r#r# #",
    "# #w# # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "# # # #r",
    " # # # #",
    "# # # # ",
    " # # # #",
    "# #W# # ",
    " # # # #",
    "#w# # # ",
    " # # # #",
    "#R#R#R# ",
    " # # # #",
    "# # #R# ",
    " # # # #",
    "# #W#W# ",
    " # # # #",
    "# # # # ",
    " # #W#W#"
    ]

for i in range(8):
    for s in range(int(len(boardLists) / 8)):
        print(boardLists[s * 8 + i], end='   ')
    print()
