
boardLists = [
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "# # # # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r# #r#r",
    " # # # #",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "# # # # ",
    "w#w#W#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#R#r#r",
    " # # # #",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "#w# # # ",
    "w# #w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r#r#r",
    " # # # #",
    "# # #w# ",
    "w#w# #w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r#r# #r",
    " # # #r#",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#",
    "#r#r#r#r",
    "r#r#r#r#",
    "#r# #r#r",
    " #r# # #",
    "# # # # ",
    "w#w#w#w#",
    "#w#w#w#w",
    "w#w#w#w#"
    ]

for i in range(8):
    for s in range(int(len(boardLists) / 8)):
        print(boardLists[s * 8 + i], end=' ')
    print()
