##DIRECTIONS##
NORTHWEST = "northwest"
NORTHEAST = "northeast"
SOUTHWEST = "southwest"
SOUTHEAST = "southeast"

WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
BLACK = (0, 0, 0)
GOLD = (255, 215, 0)
HIGH = (160, 190, 255)

FONT_ALIGN_LEFT = 0
FONT_ALIGN_CENTER = 1
FONT_ALIGN_RIGHT = 2

BUTTON_INGAME_HOVER_NONE = 0
BUTTON_INGAME_HOVER_PAUSE = 1
BUTTON_INGAME_HOVER_EXIT = 2

BUTTON_PAUSE_HOVER_NONE = 0
BUTTON_PAUSE_HOVER_CONTINUE = 3
BUTTON_PAUSE_HOVER_RESTART = 4
BUTTON_PAUSE_HOVER_EXIT = 5

BUTTON_END_HOVER_NONE = 0
BUTTON_END_HOVER_RESTART = 6
BUTTON_END_HOVER_EXIT = 7

REGION_BOARD = 8


# Custom Pygame events:
EVENT_PIECE_VANISH = 0
EVENT_PATH_END = 1

# Strings:
TURNSTRING = "Turno - {}"
WAITSTRING = "Aguarde..."
OPPONENT_NAME = "Computador"
PLAYER_NAME_DEFAULT = "Jogador"
WINDOW_CAPTION = "Damas da Perfumaria"
PAUSE_BANNER = "Jogo pausado"
PAUSE_CONTINUE = "Continuar"
PAUSE_RESTART = "Reiniciar jogo"
PAUSE_QUIT = "Sair"
ENDGAME_WIN = "Você ganhou!"
ENDGAME_LOSE = "Você perdeu..."
ENDGAME_DRAW = "Empate!"

TITLE_LINE1 = "Damas da"
TITLE_LINE2 = "Perfumaria"

TITLE_PLAYERNAME_EMPTY = "digite seu nome..."

TITLE_DIFFICULTYLABEL = "Dificuldade:"
TITLE_DIFFICULTY1 = "Principiante"
TITLE_DIFFICULTY2 = "Casual"
TITLE_DIFFICULTY3 = "Desafiador"
TITLE_DIFFICULTY4 = "Experiente"
TITLE_DIFFICULTY5 = "Mestre"

TITLE_START = "Iniciar jogo"
